internetarchive/iaux

packages/ia-components/package.json
Fix issue issue in Linux installation + Migrate to Babel 7 :tada: 
Related to PR #19 
Closes issue #16 
- Earlier there were problems in Linux installation. The problem was due to `fsevents` package.
- The babel version 6 was used. But the testing required version 7. So, the tests were failing! ([Ref](https://github.com/internetarchive/iaux/pull/19#issuecomment-475745972)).
**Solution**
- `fsevents` is moved to `optionalDependencies` which is where it should be present. 
- Migrate `Babel` from version 6 to 7
**Implementation**
Implemenation was done following the steps suggested by https://babeljs.io/docs/en/configuration
n/a
> **Testing**: Steps for …
=> Fix Linux installation problem, move fsevents to optional dependencies

packages/ia-components/index.js, packages/ia-components/sandbox/AnchorDetails.js, packages/ia-components/sandbox/tiles/ParentTileImg.js, packages/ia-components/sandbox/tiles/TileComponent.js
Remove (most) dweb dependencies from TileComponent, and adds AnchorDetails
There are still a couple of fields in TileComponent that are available in Dweb, but its unclear where they come from in a server-side implementation, especially the title of the first collection, since that is required for the text on the Parent-Collection popup image. 
Its tested in dweb-archive using both React or FakeReact, and will be pushed to live version soon. I don't have an obvious way to test in IAUX itself. 
> **Evidence**: If this PR touches UI, please post evidence (screenshot) of it …
=> Port from Dweb: Fix TileComponent and add AnchorDetails

packages/ia-components/package.json, packages/ia-components/yarn.lock
This fixes #39 - Jest not running without `babel-core`
**Technical**
Upgrade Jest to use Babel 7, so it uses `@babel/core`
**Testing**
pull down branch,
run `yarn run lerna bootstrap` at the top of the directory,
go into ia-components
run `yarn run test`
**Evidence**
Picture of Jest terminal test watcher running tests
=> Upgrade JestJS

packages/ia-components/sandbox/pagination/pagination-with-flexbox.jsx
> **Description** [hotfix]
Removes the pagination arrows and buttons from tab order to make navigation simpler for keyboard users and screen readers.
Closes #92
=> Remove pagination arrows and buttons from tab order

packages/ia-components/sandbox/theatres/components/audio-player/audio-player.less, packages/ia-components/sandbox/theatres/components/audio-player/players_by_type/archive-audio-jwplayer-wrapper.jsx
There are a few display bugs with the music player's content window -
- waveform is blocking background photo
- if no background photo, the content box is flattened
- the content box's player wrapper was holding a height, this should grow/shrink accordingly
- IA's jwplayer wrapper is too short in width, needs to be full width
**Technical**
To address the above, the following has been updated:
- content box's height is fixed when desktop view
- add a min-height to background photos
- force jwplayer to be full width as a stop gap until there is more time for Play8 updates (not ideal, but not a deal breaker)
- toggle waveform if there is background photo
=> Music Player: content box updates

packages/ia-components/sandbox/pagination/pagination-with-flexbox.jsx, packages/ia-components/sandbox/pagination/pagination.less, packages/ia-components/sandbox/theatres/components/audio-player/audio-player-main.jsx, packages/ia-components/sandbox/theatres/components/audio-player/audio-player.less, packages/ia-components/sandbox/theatres/components/audio-player/players_by_type/archive-audio-jwplayer-wrapper.jsx, packages/ia-components/sandbox/theatres/components/track-list/track-list.jsx, packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify-main.jsx, packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify.stories.js
This includes fixes specifically for these:
- Music Player, content window: background photo must hold aspect ratio
- Make pagination buttons round
- Music Player: on page load, click on highlighted track starts IA music player
JWPlayer Play8.js plumbing for:
- waveform toggle (only show waveform if no background photo is available)
- using Play8.js to set url so changing tracks between channels stay in sync
PLUS:
- data handling improvements
=> Music Player improvements + JWPlayer updates integration

packages/ia-components/sandbox/theatres/components/audio-player/audio-player.less, packages/ia-components/sandbox/theatres/components/audio-player/players_by_type/archive-audio-jwplayer-wrapper.jsx
This is a hack and should be removed once it is fixed on the IA JWPlayer Wrapper side
=> Music Player, JWPlayer: adding a black background to wrapper so controls can be seen

packages/ia-components/sandbox/theatres/components/audio-player/audio-player-main.jsx, packages/ia-components/sandbox/theatres/components/audio-player/audio-player.less, packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify-main.jsx, packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify.less, packages/ia-components/sandbox/theatres/with-youtube-spotify/utils/flatten-album-data.js, packages/ia-components/sandbox/theatres/with-youtube-spotify/utils/get-track-list-by-source.js
Fixes the following:
- Keeps `content-window` box height while changing channels
- keeps photo height, width cap at 400px
- handles portrait aspect photos
- show title in sample mp3
- omit album artist
=> Music Player updates

packages/ia-components/sandbox/AnchorDetails.js, packages/ia-components/sandbox/tiles/ParentTileImg.js, packages/ia-components/sandbox/tiles/TileComponent.js, packages/ia-components/sandbox/tiles/TileGrid.js, packages/ia-components/sandbox/tiles/TileImage.js, packages/ia-components/util.js
Several updates to components in the tile directory and the AnchorDetails - brings into line with dweb-archive prior to deleting there and using here. 
**Technical**
**Testing**
These are tested in dweb-archive but not here as dont have a way to.
**Evidence**
=> Mitra updatecomponents

packages/ia-components/sandbox/AnchorDetails.js, packages/ia-components/sandbox/tiles/ParentTileImg.js, packages/ia-components/sandbox/tiles/RelatedItems.js, packages/ia-components/sandbox/tiles/TileComponent.js, packages/ia-components/sandbox/tiles/TileGrid.js, packages/ia-components/sandbox/tiles/TileImage.js
Component suitable for bottom of Details page
**Technical**
Depends on PR #134 (updatedcomponents) so it looks more complex than it is ... once that is merged it should just be one file
Depends on the ArchiveItem and ArchiveMember controllers, but could easily be reworked to use the RelatedItem service if wanted before ArchiveItem/ArchiveMember get merged in here.
**Tested**
Its tested and live in dweb-archive
=> RelatedItems component

packages/ia-components/sandbox/pagination/pagination-with-flexbox.jsx
When paginator is on a page, it will autofocus an item.  We should not be jumping to the autofocus.
**Technical**
When `element.focus()` is called, the browser will automatically jump to make that element viewable.
We need to preserve the User's scroll position.
=> Paginator: keep page scroll fixed when autofocusing item

packages/ia-components/sandbox/theatres/components/audio-player/players_by_type/archive-audio-jwplayer-wrapper.jsx
This will allow for IA's JWPlayer Wrapper to properly setup
Significance:
Now on /details/<audioItem> load, the first track doesn't append to the URL
=> IA JWPlayer Wrapper: update config to add `responsive` flag

packages/ia-components/sandbox/details/AnchorDownload.js
Add JSDocs to AnchorDetail
**Technical**
Intended as a sample to discuss before repeating on other components. 
Note - the sample given to me https://github.com/internetarchive/iaux/blob/master/packages/ia-components/sandbox/pagination/pagination-with-flexbox.jsx#L6 hadn't got any documentation of props (it just references "see props" )
**Testing**
N/A
**Evidence**
N/A
@iisa
=> Mitra justdocs

packages/ia-components/sandbox/IAReactComponent.js
Fix a bug where IAReactComponent base class wasn't updated and so lacks the onClick function causing DetailAnchors to go to archive.org. (Hard to spot, since visual effect is correct, just URL is wrong and fails offline)
**Technical**
No changes to base class other than adding this handler
**Testing**
Tested in dweb-mirror#iaux
=> IAReactComponent add onClick handler that other components are expecting

packages/ia-components/index.js, packages/ia-components/live/example-react-component/index.js
Petabox builds are failing without this import.
Imports are failing DWEB usage of IAUX.
To simplify, we are removing this line.
=> Example Component: readding into index.js, removing experimental `classProperties` usage

packages/ia-components/package.json
Dweb components rely on this controller import.
In order for build to pass in Petabox, this needs to be included.  I have conferred with @mitra42 and the tag is the most current for this import.
I've tested local Petabox container build and is finally successful with this update.
=> Adding @internetarchive/dweb-archivecontroller

packages/ia-components/package.json, packages/ia-components/sandbox/details/DetailsCollectionList.jsx
Recent integration of `dweb-controller` is breaking PETABOX build.
This fix:
- Lints `DetailsCollectionList` - [commit](https://github.com/internetarchive/iaux/commit/334d9df8fb2593740f7dbf3dab32ffdba43af39c)
- removes the `dweb-controller` dependency
- refactored `DetailsCollectionList` to remove dependency & to accept a new prop `ArchiveMemberExpand` - [commit](https://github.com/internetarchive/iaux/commit/ce1ba69f589fe63e56f39c4a28cfed100843b3db)
Note: Look at each commit to see individual changes
**Evidence**
Image of tests passing locally:
=> Fix dweb dependency

packages/ia-components/sandbox/theatres/with-youtube-spotify/utils/archive-default-album-parser.js, packages/ia-components/sandbox/theatres/with-youtube-spotify/utils/flatten-album-data.js
Problem, Music Player not displaying tracks from album with tracks that have `.wma` extensions
Fixes: #183 
**Technical**
update view model creator to include these
**Testing & Evidence**
run storybook > go to audio player story > add in custom ID to check: /miscellaneous-music-donations-no-acoustid - the player should load with files
=> Music Player: view model creator now supports .wma files

packages/ia-components/sandbox/audio-players/audio-player.less
Problem: The search feedback text is not showing up appropriately.
This is part of #172 
**Technical**
**Testing**
- fix the CSS
Go to: https://www-isa.archive.org/details/cd_trail-of-memories-the-randy-travis-antholo_randy-travis-b.b.-king-george-jones-merle
click liner notes tab > search "Randy" > you will see text in progress bar like the photo
=> Music Player, liner notes: make sure search messaging displays

packages/ia-components/sandbox/audio-players/archive-audio-jwplayer-wrapper.jsx, packages/ia-components/sandbox/audio-players/audio-player-main.jsx, packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify-main.jsx
- Play8 `onSetupComplete` sends custom callback that signals what track jwplayer starts on
- only fires `PlayN` when user selects track or when track auto advances
- keeps player element on page so it matches the `Play` instance that it creates on first mount for the whole session
=> Jwplayer round3

packages/ia-components/sandbox/bookreader-component/bookreader-wrapper-main.jsx
Problem: The `this` in the `getPageURL` function was lost in Reactland.
Solution: pass in the `br` instance that was created
**Testing**
go to: https://www-isa.archive.org/details/cd_the-best-of-anita-baker_anita-baker-the-winans
and LP : https://www-isa.archive.org/details/lp_the-classic-jazz-quartet_the-classic-jazz-quartet
Liner notes should display.  This is especially for a fix for the LPs where the original sizes are massive.
**Evidence**
=> Fix scope issue in liner notes scaling

packages/ia-components/sandbox/audio-players/youtube-player.jsx
Subtask of #213
**Technical**
Uses setTimeout() to display the error for a longer time, before switching on to the next task.
**Evidence**
=> Add time delay for displaying error

packages/ia-components/sandbox/audio-players/archive-audio-jwplayer-wrapper.jsx, packages/ia-components/sandbox/audio-players/audio-player-main.jsx, packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify-main.jsx
Problem:
The URL Setter function fired at every channel change.
Solution:
- Abstract URL Setter to main controller `<AudioWithYouTubeSpotify/>` to have better control when it fires
- Simplify channel selector function
- Clean up errors (adding props, linting, code reorg, etc.)
**Testing**
Test Repro steps here: https://webarchive.jira.com/browse/WEBDEV-2439
=> Music Player: fix autoplay when changing channels

packages/ia-components/sandbox/audio-players/youtube-player.jsx
Closes #223  
Clears timeout to prevent it from running when the next track is selected.
=> Clear timeout when new track selected

packages/ia-components/sandbox/audio-players/youtube-player.jsx
Closes #222 
Stops automatically playing the youtube player after changing channels.
=> Stop autoplaying the youtube player after changing channels

packages/ia-components/index.less, packages/ia-components/sandbox/audio-players/archive-audio-jwplayer-wrapper.jsx, packages/ia-components/sandbox/audio-players/audio-player-main.jsx, packages/ia-components/sandbox/audio-players/audio-player.stories.js, packages/ia-components/sandbox/audio-players/third-party-embed.jsx, packages/ia-components/sandbox/audio-players/youtube-player.jsx, packages/ia-components/sandbox/audio-players/youtube-player.less, packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify-main.jsx, packages/ia-components/sandbox/theatres/with-youtube-spotify/utils/get-track-list-by-source.js
Closes #178 
**Technical**
Adds the youtube player to IAUX.
=> Merge YouTube API integration (178) into master

packages/ia-components/sandbox/audio-players/archive-audio-jwplayer-wrapper.jsx, packages/ia-components/sandbox/audio-players/audio-player-main.jsx, packages/ia-components/sandbox/audio-players/audio-player.less, packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify-main.jsx
Adding Handling for JWPlayer when there are no tracks to play.
Closes #214 
This is a part of https://webarchive.jira.com/browse/WEBDEV-2331
**Technical**
- extract inline styling and add it to css
- add a new prop into `<AudioPlayerMain/>`: `hasTracks`
- to signify which class the audio player needs
- In `<ArchiveJWPlayerWrapper>`, do not instantiate JWPlayer/Play8 if there aren't any tracks
**Testing & Evidence**
=> Music Player, JWPlayer: If there aren't any tracks, do not show or instantiate the player

packages/ia-components/sandbox/audio-players/audio-player-main.jsx, packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify-main.jsx
Closes #230
Verifies a track number's presence in the youtube/spotify channel before sending it to their respective wrapper, if not present sends the next track in order.
=> Check track before sending to youtube wrapper or spotify

packages/ia-components/sandbox/audio-players/youtube-player.jsx, packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify-main.jsx
YouTube wrapper behavior fine tuning.
This PR ensures the following:
1) On page load, changing channels does not update track nor autoplay
2) On page load, changing channel to YouTube, clicking on the selected track plays the video
#1 & 2) Can be tested on:
`https://www-isa.archive.org/details/cd_backstreet-boys_backstreet-boys/disc1/03.+Backstreet+Boys+-+Get+Down+(You're+The+One+For+Me).flac`
&&
`https://www-isa.archive.org/details/cd_backstreet-boys_backstreet-boys`
Repro Steps:
- load page
- change channel to YouTube
- change channel back to Internet Archive
- basically, any channel change on load should NOT pollute URL. should not autoplay YouTube.
- NOW, change back to YouTube
- click on highlighted track,
- video will play
=> Music Player - updating onload management of track availability

packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify-main.jsx, packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify.stories.js, packages/ia-components/sandbox/track-lists/track-list.jsx
Music Player - track artist update
Removes the dependency of the first artist being listed in the album creator list as the main artist.
This checks the following:
- Do not show track artist if it matches the album artist
- Do not show track artist if track artist mastches the album artist
**Technical**
**Testing**
You can run storybook and check the examples to see updates.
**Evidence**
Compilations show ALL the artists in the track list:
Best of albums do not show main artist:
Classical compilations can vary, and we will err in the side of redundancy:
=> Track listing artist update

packages/ia-components/sandbox/pagination/utils/dom-dimensions.js, packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify.stories.js
Page calculation can only do so much with JS math.
This case happens when, in extra wide view, the track listing columns are larger than 3 and less than 6.
The container's scrollWidth / containerWidth will not detect that other necessary page.
So we must make sure we have a case for it.
**Technical**
**Testing & Evidence**
Load Storybook, go to music player example, click on pre-loaded id: illegal-art
BEFORE -- Paginator doesn't show up:
AFTER -- Paginator shows up:
=> Paginator - 3 column wide view pages well

packages/ia-components/sandbox/audio-players/utils/youtube-params-parser.js, packages/ia-components/sandbox/audio-players/youtube-player.jsx, packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify-main.jsx, packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify.stories.js, packages/ia-components/sandbox/theatres/with-youtube-spotify/utils/get-track-list-by-source.js, packages/ia-components/sandbox/track-lists/track-list.jsx
Fixes included in this PR:
Problem:
Full Album is not highlighted when selected in 3rd party channel - `archive.org/details/cd_aaliyah_aaliyah-static-from-playa-timbaland`
Solution:
url 1: `https://www-isa.archive.org/details/cd_aaliyah_aaliyah-static-from-playa-timbaland/disc1/02.+Aaliyah%3B+Static+From+Playa+-+Loose+Rap.flac`
url 2: `https://www-isa.archive.org/details/cd_aaliyah_aaliyah-static-from-playa-timbaland`
QA notes:
- onload `/details/:id` OR `/details/:id/:track` > changing channels >
- track 1 will be highlighted if its available in the channel
- NO change to URL
- onload `/details/:id/:track` > change channel > select "Full Album" track 
- URL will not change
- onload `/details/:id/:track` > change channel > select "Full Album" track > change channels 
- channel that …
=> Multiple music player bug fixes (per commit)

packages/ia-components/sandbox/audio-players/archive-audio-jwplayer-wrapper.jsx, packages/ia-components/sandbox/audio-players/audio-player-main.jsx, packages/ia-components/sandbox/audio-players/utils/youtube-full-album-registry.js, packages/ia-components/sandbox/audio-players/youtube-player.jsx, packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify-main.jsx
When a full album is available, IA segments each track using timestamps on that full album video.
This extends our current YouTube player to handle this issue.
BONUS! - updates to jwplayer wrapper to make a better experience.
**Technical**
- New file: `youtube-full-album-parser.js` checks the youtube playlist and creates a dictionary of params to pass to the YouTube API.  If not, it returns null.
**Testing**
Go to item with a full album: `https://www-isa.archive.org/details/wcd_unresolved-childhood_screw-32_flac_lossless_29945541/Screw+32+-++Unresolved+Childhood+Issues+(1995)+%5BFLAC%5D/03+-+Old+Idea+New+Head.flac`
- onload, playing video directly OR clicking on highlighted track OR clicking on unhighlighted track should start autoadvance.
- track list adapts to changes on …
=> Youtube full album handler & Overall Flow Management

packages/ia-components/sandbox/audio-players/youtube-player.jsx
Problem:
At times, you can hear blips when playing a long YouTube video
Solution:
reduce time number of times calls to change the url happen
**Testing**
go to: `https://www-isa.archive.org/details/cd_dark-side-of-the-moon_pink-floyd/disc1/05.+Pink+Floyd+-+Money.flac` > go to YouTube channel > play track > turn volume off > should not hear any blips
=> YouTube player, reduce direct pings to jwplayer to set url when track autoadvances happens

packages/ia-components/sandbox/audio-players/youtube-player.jsx, packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify-main.jsx
Problem:
Callbacks for pinging YouTube API & URL changer lost their instance component state
This caused extra firings of calls that were not necessary.
UI Symptom was an audible blip happening every few seconds during a YouTube video
Solution:
Pin callbacks to class state so that it can make the correct checks for tracks when they need to
**Test steps**
go to: https://www-isa.archive.org/details/cd_huangxiao/disc1/13.+%E9%BB%83%E5%B0%8F%E6%A5%A8+-+%E8%B3%9E%E5%91%B3%E6%9C%9F%E9%99%90.flac
- open dev tools to show console
- change to YouTube channel
- play track
- move youtube video scrubber around > `playN` from line 562 only fires once in console
- click any track on the track listing > `playN`  from line 562 only fires once in console
- click 1st track > use video scrubber to go to …
=> YouTube callbacks keeping instance internal state

packages/ia-components/integration/example.test.js, packages/ia-components/integration/jest.config.js, packages/ia-components/integration/jestConfigAfterEnv.js, packages/ia-components/package.json, packages/ia-components/yarn.lock
Adds Selenium Webdriver for use within Jest test framework. Tests are to be placed within "packages/ia-components/integration" and given a suffix of ".test.js". All integration tests are run from within packages/ia-components with `yarn run test:integration`
Closes #263 
**Technical**
Currently, integration tests will have to be written to request the Storybook server (localhost:9001 by default). May want to abstract to a config option or environment variable to easily override if we use CI to test.
**Testing**
• `cd packages/ia-components && yarn install`
• `yarn run test:integration`
**Evidence**
=> Adds Selenium Webdriver

packages/ia-components/sandbox/details/AnchorDownload.jsx, packages/ia-components/sandbox/details/AnchorSearch.jsx, packages/ia-components/sandbox/details/Image.jsx, packages/ia-components/sandbox/details/NavWrap.jsx, packages/ia-components/sandbox/tiles/TileComponent.jsx, packages/ia-components/util.js
Handle bug in ImageDweb when React calls the ref= without an element
**Technical**
React seems to occasionally call its ref= function with the element set to null, handles that for Image Dweb. 
**Testing**
**Evidence**
=> Handle bug in ImageDweb when React calls the ref= without an element

packages/ia-components/sandbox/theatres/with-youtube-spotify/utils/archive-default-album-parser.js, packages/ia-components/sandbox/theatres/with-youtube-spotify/utils/archive-lp-album-parser.js, packages/ia-components/sandbox/theatres/with-youtube-spotify/utils/flatten-album-data.js, packages/ia-components/sandbox/theatres/with-youtube-spotify/utils/utils.js, packages/ia-components/sandbox/theatres/with-youtube-spotify/utils/utils.test.js
WEBDEV-2608
In music player, where we parse the data, extend to validate the major audio file extensions
**Technical**
Create a utils.js file to house the validators for sharing across files
**Testing**
Currently on-site, it does not show all of the tracks
archive.org/details/cd_bbc-radio-1967-1971_soft-machine
Go to:
https://www-isa.archive.org/details/cd_bbc-radio-1967-1971_soft-machine
Confirm that all the tracks show.
=> Music Player - formalize file extension validator

packages/ia-components/sandbox/theatres/with-youtube-spotify/utils/flatten-album-data.js, packages/ia-components/sandbox/theatres/with-youtube-spotify/utils/flatten-album-data.test.js
Last filter fix accidentally ( 😬 ) excluded image files.  This fixes it.
**Technical**
Music player files filtering includes images now + unit test to ensure its existence.
**Testing**
Locally: run storybook > go to theatre > content window will show cover image when it is available.
Staging:
fix: https://www-isa.archive.org/details/cd_2004-promotional-cd_afroman
orig: https://archive.org/details/cd_2004-promotional-cd_afroman
=> Music Player - Files Filter must include image files + switch test to use expect

packages/ia-components/sandbox/data-for-stories/album-private-with-spotify-youtube.js, packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify.stories.js, packages/ia-components/sandbox/theatres/with-youtube-spotify/utils/archive-derived-album-parser.js, packages/ia-components/sandbox/theatres/with-youtube-spotify/utils/flatten-album-data.js, packages/ia-components/sandbox/theatres/with-youtube-spotify/utils/flatten-album-data.test.js, packages/ia-components/sandbox/track-lists/track-list.jsx
Music Player files parser updates:
- use /metadata schema to do transformations. This will get us closer to allow @mitra42 and DWEB client to user player
- remove collection-based switch to toggle between the 2 parsers we have.
https://webarchive.jira.com/browse/WEBDEV-2638
**Technical**
Parser tests run through `flatten-album-data.test.js` at this time.
We will continue to have 2 different parser files so we can separate logic into something we can understand.
**Testing**
run storybook > go to theatre stories > check this identifier: `national_lampoon_thats_not_funny_thats_sick` > player should show correctly with track listing
=> Audio player files parser update

packages/ia-components/sandbox/selectors/horizontal-radio-group/horizontal-radio-group.jsx, packages/ia-components/sandbox/selectors/horizontal-radio-group/horizontal-radio-group.less
Fixes https://webarchive.jira.com/browse/WEBDEV-2574
**Technical**
The click event on items in the horizontal radio group fired twice because the radio element was inside of the label element. The change event simulates a click event on parent elements. Moving it just before the label and changing the CSS selector chain for checked state prevent the second click event firing.
**Testing**
See Jira ticket above
**Evidence**
=> Moves radio element out of label to prevent double event firing

packages/ia-components/sandbox/theatres/with-youtube-spotify/utils/flatten-album-data.js
We are starting to use the music player with collections that are mixed with restricted & non restricted items.
That means, we need to move music player out of handling only restricted items.
This shift is described here: https://webarchive.jira.com/browse/WEBDEV-2687
**Technical**
In the file parser, we will add another check to make sure we are correctly using the right one.
**Testing**
Check Before: `https://58-review-webdev-268-75hs41.archive.org/details/deathofsalesmans00mill`
Test After:
Load storybook > go to theatre > load music player > scroll past Willie Nelson and add this identifier to the ad-hoc input field: `deathofsalesmans00mill`
Track list should look like this:
=> music player, data parser: handle items that aren't restricted with samples

packages/ia-components/live/example-react-component/example.test.js, packages/ia-components/package.json, packages/ia-components/yarn.lock
Swap out assert to expect and remove assert dependency.
#242 Replaced 'assert' to 'expect' and removed assert depency.
**Technical**
The method assert was removed and replaced to expect from Jest. Also assert dependency was removed because is not used anymore.
**Testing**
Run 'yarn:test' and check 'example-react-component/example.test.js' is 100% coveraged.
**Evidence**
=> Replace assert to expect function test

packages/audio-element/audio-element.js, packages/audio-element/index.d.ts, packages/audio-element/index.js, packages/audio-element/package.json, packages/audio-element/src/audio-element.ts, packages/audio-element/stories/index.stories.js
> This adds a few types to the audio-element and adds a declarations file so other TypeScript projects can use it as a typed object.
**Technical**
> Mostly just TypeScript-related updates
**Testing**
> Check out the `audio-element-updates` branch of the repo, `cd packages/audio-element`, `yarn start` and you can play with the Audio Element.
> Run `yarn test` to run the unit tests.
**Evidence**
> n/a
=> Audio Element: Add Types and Declaration File

packages/transcript-view/demo/index.html, packages/transcript-view/index.d.ts, packages/transcript-view/index.js, packages/transcript-view/package.json, packages/transcript-view/src/models/transcript-config.ts, packages/transcript-view/src/models/transcript-entry-config.ts, packages/transcript-view/src/transcript-entry.ts, packages/transcript-view/src/transcript-view.ts, packages/transcript-view/test/transcript-view.test.js, packages/transcript-view/transcript-view.js
> This re-adds the TranscriptView config to wrap the transcript entries array. This is useful for passing additional data into transcript without adding a bunch more properties.
> This also adds support for music sections where we skip parts of the program because music is playing.
> It also fixes some scroll issues, as well as adds a TypeScript declarations file so other TS projects can import it easily..
**Technical**
> This adds a TypeScript declarations file for consumption by other TS projects.
**Testing**
> Check out the `transcript-view-updates` branch of the repo, `cd packages/transcript-view`, `yarn start` and you can play with the transcript view.
> Run `yarn test` to run the unit tests.
**Evidence**
> The UI looks the same as previous version, just some …
=> Transcript View: Add Transcript View Config, Music Sections, TypeScript Declarations, and Fix Scrolling

packages/audio-element/package.json, packages/playback-controls/package.json, packages/scrubber-bar/package.json, packages/transcript-view/package.json, packages/waveform-progress/package.json
> In order to make a package public on NPM, you have to add `publishConfig` to `package.json`
**Technical**
> n/a
**Testing**
> n/a
**Evidence**
> <img width="861" alt="Screen Shot 2019-10-09 at 2 30 42 PM" src="https://user-images.githubusercontent.com/51138/66522057-64020900-eaa1-11e9-9b6a-280dcb5cdc90.png">
=> Add Public Access Control for NPM

packages/ia-components/jest.config.js
This will allow for unit tests to pass through CI
**Technical**
- updating jest config file to ignore directory
**Testing**
pull down branch, run: `yarn run test:watch` => all tests pass
**Evidence**
=> Temporarily ignoring selenium tests in Jest

packages/audio-element/src/audio-element.ts
> We don't want events to escape their shadowRoot. This prevents them from leaking up to parent listeners.
**Technical**
> n/a
**Testing**
> n/a
**Evidence**
> n/a
=> Audio Element: Stop Bubbling of Events

packages/scrubber-bar/demo/index.html, packages/scrubber-bar/index.js, packages/scrubber-bar/package.json, packages/scrubber-bar/src/assets/img/next-section-marker.ts, packages/scrubber-bar/src/assets/img/previous-section-marker.ts, packages/scrubber-bar/src/scrubber-bar.ts, packages/scrubber-bar/src/section-marker.ts, packages/scrubber-bar/test/promised-sleep.js, packages/scrubber-bar/test/scrubber-bar.test.js, packages/scrubber-bar/test/section-marker.test.js
> This adds optional section markers to the scrubber that denote different sections in the playback.
**Technical**
> n/a
**Testing**
> Run `yarn install`, `yarn test` to run the tests. Run `yarn start` to play with it in the browser.
**Evidence**
> ![Screen Shot 2019-10-29 at 3 48 01 PM](https://user-images.githubusercontent.com/51138/67815302-d42dfa00-fa63-11e9-92d5-21913a23276d.png)
=> Scrubber Bar: Add Section Markers

packages/playback-controls/demo/index.html, packages/playback-controls/package.json, packages/playback-controls/src/assets/img/next-section.ts, packages/playback-controls/src/assets/img/previous-section.ts, packages/playback-controls/src/playback-controls.ts, packages/playback-controls/test/playback-controls.test.js
> This adds two buttons for going backwards and forwards by section.
**Technical**
> Adds new SVGs and emits events when the buttons are pressed.
**Testing**
> Run `yarn install`, `yarn test` to run the tests. Run `yarn start` to play with the controls in the browser.
**Evidence**
> ![Screen Shot 2019-10-29 at 3 31 07 PM](https://user-images.githubusercontent.com/51138/67814684-e6a73400-fa61-11e9-838b-553c16e84ee6.png)
=> Playback Controls: Add Controls for Jumping Through Sections

.travis.yml, README.md, packages/audio-element/karma.conf.js, packages/audio-element/package.json, packages/audio-element/yarn.lock, packages/expandable-search-bar/karma.conf.js, packages/expandable-search-bar/package.json, packages/expandable-search-bar/yarn.lock, packages/playback-controls/karma.conf.js, packages/playback-controls/package.json, packages/playback-controls/yarn.lock, packages/radio-player/karma.conf.js, packages/radio-player/package.json, packages/radio-player/yarn.lock, packages/scrubber-bar/karma.conf.js, packages/scrubber-bar/package.json, packages/scrubber-bar/yarn.lock, packages/transcript-view/karma.conf.js, packages/transcript-view/package.json, packages/transcript-view/yarn.lock, packages/waveform-progress/karma.conf.js, packages/waveform-progress/package.json, packages/waveform-progress/yarn.lock
> Add CodeCov support for tracking code coverage.
**Technical**
Three main changes:
1. Install codecov CLI tool while running TravisCI
2. Install the `karma-coverage` plugin for all of the radio player components and configure it. The majority of the size of this MR is just `yarn.lock` updates for it.
3. After tests have run, run `codecov` CLI tool and it finds the coverage files in the entire repo
**Testing**
> There should be a Codecov report below
**Evidence**
> Check out the Codecov report below! Also, click through to https://codecov.io/gh/internetarchive/iaux to see more info
=> Add CodeCov Support

packages/ia-components/variables.less
This increases the width range of the desktop breakpoint to account for both BookReader controls being visible and track lists being rendered nicely when long track names are present. Closes [WEBDEV-3056](https://webarchive.jira.com/browse/WEBDEV-3056)
**Testing**
See Jira ticket
=> Increases desktop max and widescreen min widths

packages/radio-player/package.json, packages/radio-player/yarn.lock, packages/transcript-view/src/transcript-view.ts, packages/transcript-view/test/transcript-view.test.js
> This fixes a bug in the transcript scroll where it would sometimes look like it was stuttering while it was scrolling.
**Technical**
> The cause of this issue is the revamped search code. We can now have more than one transcript entry highlighted at a time and the logic to determine which entry to highlight was basically causing the "scroll target" to constantly change so it would stutter while it was adjusting the scroll speed and duration.
**Testing**
1. Go to https://58-review-radio-play-lpp4ra.archive.org/details/Euronews_Radio_English_20190427_170000
2. Hit the Play Button
3. Scroll to the bottom of the transcript
4. Tap "Scroll text with audio"
5. Expected: It should not stutter while it scrolls.
**Evidence**
=> Transcript Scrolling Fix

packages/radio-player/demo/radio-player-controller.ts, packages/radio-player/src/models/radio-player-config.ts, packages/radio-player/src/radio-player.ts, packages/radio-player/test/radio-player.test.js
> If the radio program does not have a waveform image, don't display the waveform component.
**Technical**
> n/a
**Testing**
> Go to https://58-review-radio-play-lpp4ra.archive.org/details/BBC_Radio_5_Live_20191029_000000 and you shouldn't see a broken waveform
**Evidence**
>
=> Radio Player: Don't Display the Waveform if one is not Available

packages/radio-player/src/radio-player.ts
> Fix the mute setting in the volume control.
**Technical**
> Since the volume can be `0`, we have to specifically check for `undefined` instead of just falsey.
**Testing**
1. With an admin archive.org email user
2. Visit https://58-review-radio-play-lpp4ra.archive.org/details/VOA_Global_English_20170803_190000?start=0
3. Play and make sure you can mute the volume.
**Evidence**
> n/a
=> Radio Player Mute Fix

packages/ia-components/.storybook/preview-head.html
The path to BookReader-ia.css was incorrect.
**Testing**
Run `yarn run storybook` from within packages/ia-components. Open developer tools from the Storybook page. View the resolved request to https://archive.org/bookreader/BookReader-ia.css
=> Fixes BookReader CSS reference

packages/ia-components/.storybook/middleware.js, packages/ia-components/package.json, packages/ia-components/yarn.lock
Upgrades to latest proxy middleware and updates Storybook middleware to use new middleware method.
**Testing**
Run `yarn run storybook` within packages/ia-components and view log output. Rewrite rules should appear in the format of `[HPM] Proxy rewrite rule created: "^/details" ~> "https://archive.org/details"`
=> Upgrades http-proxy-middleware to latest

packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify.less
Adds vendor-prefixed CSS properties to support IE11.
**Testing**
See https://webarchive.jira.com/browse/WEBDEV-3229
**Evidence**
https://58-review-webdev3075-behvpo.archive.org/details/cd_experience-hendrix-the-best-of-jimi-hendri_jimi-hendrix-the-jimi-hendrix-experience?transpiled=1 renders the audio player layout as intended.
=> Adds IE grid properties to audio player

packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify.less
The Less compiler reads a compressed definition of grid-columns as a media query and fails. Instead, a hard-coded repeated value for grid columns needs to be used.
https://git.archive.org/ia/petabox/-/jobs/251748 shows an example of it failing.
=> Changes ms-grid-columns syntax to get around bug in Less compilation

packages/ia-components/CHANGELOG.md, packages/ia-components/package.json, packages/ia-components/scripts/postversion.js, packages/ia-components/scripts/version.js
Adds version and postversion scripts to make tagging releases in GitHub easier.
Closes #332 . 
**Technical**
Version number should first be updated in package.json. Once updated, running `npm run version` will write a release message placeholder to CHANGELOG.md. Replace with your release message, save CHANGELOG.md, then press a key at the prompt. A browser window should open with the release info prefilled, the URL copied to the clipboard, and rendered to the terminal output.
**Testing**
Run `npm run version`
=> Creates ia-components release script

packages/radio-player/src/radio-player.ts, packages/radio-player/test/radio-player.test.js
> We were dispatching events from several of the components like scrubber bar scrubs and transcript entry selections, but not the playback controls.
This adds some event dispatches and tests for them.
**Technical**
> It is mainly re-dispatching events for the consumer to handle or track.
**Testing**
> Nothing to test. There are unit tests verifying that the events are being emitted.
=> Dispatch Events from the Playback Controls to the Radio Player Consumer

packages/ia-topnav/index.html, packages/ia-topnav/package.json, packages/ia-topnav/src/styles/dropdown-menu.js, packages/ia-topnav/src/styles/search-menu.js
Adjusts search menu styles and removes example HTML overflow to catch any unexpected container overflow. The existing closed state of the search menu positions it left 100%, which always extends the effective topnav width (and the entire page) by at least 40px, causing a horizontal scrollbar to appear. Instead, the initial top value is set to position it off top top of the document until open.
=> Moves search menu offscreen at desktop breakpoint

packages/ia-topnav/test/search-menu.test.js
Adds a test for `config.hiddenSearchOptions`
**Testing**
Checkout the branch and run `yarn test`. Open "coverage/index.html", navigate to src/search-menu.js and note 100% test coverage
=> Adds test for hiddenSearchOptions

packages/ia-topnav/.npmignore, packages/ia-topnav/README.md, packages/ia-topnav/index.html, packages/ia-topnav/src/constants.js, packages/ia-topnav/src/data/menus.js, packages/ia-topnav/src/desktop-subnav.js, packages/ia-topnav/src/ia-topnav.js, packages/ia-topnav/src/login-button.js, packages/ia-topnav/src/media-button.js, packages/ia-topnav/src/media-subnav.js, packages/ia-topnav/src/more-slider.js, packages/ia-topnav/src/nav-search.js, packages/ia-topnav/src/primary-nav.js, packages/ia-topnav/src/search-menu.js, packages/ia-topnav/test/more-slider.test.js, packages/ia-topnav/test/primary-nav.test.js
On archive.org, the static markup of ia-topnav rendered via Rendertron is inserted as a child of ia-topnav. When the custom elements are later defined, each of those elements are separately initialized with an empty config object. As a result, the `baseUrl` config param is undefined and some assets no longer point to the correct location. This introduces a constant, `prodUrl`, that is used as a fallback for the primary and sub navigation items.
**Testing**
Run the app and remove `baseUrl` from index.html. The links and image sources should all point to `prodUrl`.
=> Adds production host constant for default baseHost value

packages/ia-topnav/package.json, packages/ia-topnav/src/primary-nav.js, packages/ia-topnav/test/ia-topnav.test.js, packages/ia-topnav/test/primary-nav.test.js
Two remaining `baseUrl` references were present in `<primary-nav>`. Fixed and added tests to prevent regressions.
=> Fixes references to baseUrl in primary-nav

packages/ia-topnav/package.json, packages/ia-topnav/src/styles/dropdown-menu.js
Sets a max height and overflow on dropdowns so they scroll when the list exceeds the viewport height. This is necessary for instances when the topnav is set in a fixed position as it is in the TV archive pages.
=> Sets max height on dropdowns

packages/ia-topnav/package.json, packages/ia-topnav/src/nav-search.js, packages/ia-topnav/src/primary-nav.js, packages/ia-topnav/test/nav-search.test.js
TV caption search is handled through a query param from the TV details page rather than search.php. In the event TV is the selected search type, the `locationHandler` function should be used to redirect to the TV details page with the query as a param in the form of `?q=query`
=> Adds location handler for searching TV captions

packages/ia-topnav/package.json, packages/ia-topnav/src/primary-nav.js, packages/ia-topnav/src/styles/primary-nav.js, packages/ia-topnav/src/styles/signed-out-dropdown.js, packages/ia-topnav/src/styles/user-menu.js, packages/ia-topnav/test/nav-search.test.js
In order to provide enough horizontal space for all nav items, at < 990px viewport width the upload and username text labels should be hidden. This behavior exists on the current live nav, and provides just enough room for the signed out version of nav.
=> Hides upload and user labels below 990px

packages/ia-topnav/package.json
Publishes new release of ia-topnav.
* Design changes to address viewport width causing media menu to break to new line
=> Releases ia-topnav 0.2.8

packages/radio-player/demo/radio-player-controller.ts, packages/radio-player/src/search-handler/search-handler.ts, packages/radio-player/test/search-handler/search-handler.test.js
> Fixes an issue in the Radio Archive search where we wouldn't rebuild the transcript properly.
**Technical**
> The search engine didn't always return search results in order from start to end, but when we rebuild the transcript, we do so from start to end. This would cause the transcript rebuild to stick parts of the transcript in the wrong spot. The solution was to sort the results.
**Testing**
> For certain queries, the transcript should be correct now
=> WEBDEV-3319 Radio Archive Transcript Search Fix

packages/radio-player/karma.bs.config.js, packages/radio-player/karma.conf.js, packages/radio-player/package.json, packages/radio-player/yarn.lock
The version of `karma-esm` we had installed had a bug where it did not pass the `preserveSymlinks` flag through to the `es-dev-server` when tests were running.
This caused tests to fail when the dependencies were symlinked, such as through `lerna bootstrap`.
This sets the `preserveSymlinks` flag and updates `karma-esm`.
---
This started because we are now using semantic versions of all of the radio player dependencies and Lerna symlinks them instead of installing them from npmjs as it does with canary versions. The tests were failing, but not being reported as failures.
=> Fix Radio Player Tests

packages/ia-topnav/package.json, packages/ia-topnav/src/primary-nav.js, packages/ia-topnav/test/ia-topnav.test.js, packages/ia-topnav/test/primary-nav.test.js
To eliminate the need to send in two values for screen name (one for display, one for URL building), the screen name truncation is now moved from Petabox to the nav component.
=> Renders truncated screen name in topnav

packages/ia-topnav/src/styles/media-menu.js
<media-menu> previously used vh units to position off screen for mobile breakpoints. When the viewport height was too short, however, the bottom edge would still be visible. This sets a fixed pixel value that slightly exceeds the height of the media menu to ensure it remains completely off screen when closed.
See animation, which colors the media menu red for demonstration.
=> Uses fixed measurement position for media menu on mobile

packages/ia-topnav/package.json, packages/ia-topnav/src/data/menus.js
Changes the NEL link back to "Books to Borrow"
=> Change NEL back to "Books to Borrow"

packages/ia-topnav/README.md, packages/ia-topnav/base64_encoded_menus.html, packages/ia-topnav/index.html, packages/ia-topnav/src/nav-search.js, packages/ia-topnav/test/nav-search.test.js
When `config.searchQuery` is set, the value of the search input will be populated with its value. This is to be used to prepopulate the search form with an existing search query in Petabox. See https://webarchive.jira.com/browse/WEBDEV-3594 for details.
=> Adds searchQuery property on config object

packages/ia-topnav/base64_encoded_menus.html, packages/ia-topnav/package.json, packages/ia-topnav/src/ia-topnav.js
To make it easier to transport the data from Petabox to the nav, base64 encoding has been added on the Petabox side. This adds the same type of property converter to config that is already present on the menus.
=> Adds base64 decoding converter to config property

lerna.json, packages/ia-topnav/karma.conf.js
> Test if setting the test concurrency fixes the unit test failures.
**Technical**
> The reason the tests were failing is because `lerna` tries to run the tests in parallel, but if you have too many test runners running all at once, they conflict with one another. Setting the concurrency to 1 slows it down, but the tests pass.
**Testing**
> No testing needed. The unit tests should pass.
**Evidence**
=> Fix Tests by Setting Test Concurrency

.travis.yml
Currently when you open an PR, Travis does 2 runs: one just for the branch and one for the PR. We don't need the branch run separately since we're interested in the PR run.
=> Only run Travis builds for PRs and master branch

packages/ia-components/bin/copy_bookreader.js, packages/ia-components/package.json, packages/ia-components/sandbox/bookreader-component/bookreader-wrapper-main.jsx, packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify.less, packages/ia-components/yarn.lock, packages/radio-player/yarn.lock
Replaces the Petabox inherited styles for the BookReader wrapper with component-specific styles. Fixes [WEBDEV-3733](https://webarchive.jira.com/browse/WEBDEV-3733)
**Technical**
Upgrades BookReader to latest version in dev dependencies.
**Testing**
Run Storybook, view the audio player theater in Safari, and toggle fullscreen in BookReader. The full theater area should be used for BookReader.
**Evidence**
=> Webdev 3733 fixes safari fullscreen

packages/ia-topnav/src/nav-search.js, packages/ia-topnav/test/nav-search.test.js
The `sin` param should not be sent with a metadata (default) search. This conditionally renders the hidden field based on the presence of a `searchIn` property being set. Fixes [WEBDEV-3595](https://webarchive.jira.com/browse/WEBDEV-3595)
**Testing**
Run the demo server and submit a metadata search. The `sin` param should not be present in the resulting archive.org redirect. Choose a different search in value and submit a search. The `sin` param should be filled in for other values excepting TV. TV has a unique URL structure that remains unchanged.
**Evidence**
=> Conditionally renders sin input

packages/ia-topnav/README.md, packages/ia-topnav/base64_encoded_menus.html, packages/ia-topnav/index.html, packages/ia-topnav/package.json, packages/ia-topnav/src/data/menus.js, packages/ia-topnav/src/desktop-subnav.js, packages/ia-topnav/src/dropdown-menu.js, packages/ia-topnav/src/ia-topnav.js, packages/ia-topnav/src/lib/formatUrl.js, packages/ia-topnav/src/login-button.js, packages/ia-topnav/src/media-button.js, packages/ia-topnav/src/media-menu.js, packages/ia-topnav/src/media-slider.js, packages/ia-topnav/src/media-subnav.js, packages/ia-topnav/src/more-slider.js, packages/ia-topnav/src/nav-search.js, packages/ia-topnav/src/primary-nav.js, packages/ia-topnav/src/search-menu.js, packages/ia-topnav/src/wayback-slider.js, packages/ia-topnav/test/ia-topnav.test.js, packages/ia-topnav/test/more-slider.test.js, packages/ia-topnav/test/wayback-slider.test.js, packages/ia-topnav/yarn.lock, packages/ia-wayback-search/README.md, packages/ia-wayback-search/index.html, packages/ia-wayback-search/package.json, packages/ia-wayback-search/src/ia-wayback-search.js, packages/ia-wayback-search/test/wayback-search.test.js
In order to allow the change of the base host for most links in the topnav, a property needs to be added to the ia-topnav component. This is also passed in to the ia-wayback-search component, which receives the same property addition. A function is added to lib to check whether the URL being used is fully qualified or not, and if not, uses the baseHost property to build a full URL.
**Testing**
Visit https://www-shaner5.archive.org/. All URLs that would normally be root relative use the www-shaner5 subdomain. If you then change the property with `document.querySelector('ia-topnav').baseHost = 'archive.onion'`, those same URLs should update to use the new baseHost.
=> Extracts base host to prop

packages/ia-topnav/index.html, packages/ia-topnav/src/constants.js, packages/ia-topnav/src/data/menus.js, packages/ia-topnav/src/ia-topnav.js, packages/ia-topnav/src/lib/formatUrl.js, packages/ia-topnav/src/primary-nav.js
> Previously, the top nav was writing out an `https://` prefix to all of the URLs so we couldn't make the links relative if we wanted to.
**Technical**
> This changes the base URL so the consumer should now pass in the protocol as well
**Testing**
> Checkout the repo, go to `packages/ia-topnav`, run `yarn install`, run `yarn start` and you should see a demo of it. You can click the "Change Base Host" button in the demo and it will change the URLs to use the new base host
=> Update Topnav Base Host handling

packages/ia-components/sandbox/bookreader-component/bookreader-wrapper-main.jsx
- getPageURI should use argument instead of internal bookreader property
- getPageURI should only use powers of 2 for reduce
**Technical**
Blocker for https://github.com/internetarchive/bookreader/pull/646
**Testing**
Available for testing with https://github.com/internetarchive/bookreader/pull/646 at e.g. https://ia-petabox-drini.archive.org/details/lp_chant-of-the-jungle_august-colon . Things to note:
1) Zooming in loads higher res copies.
2) Urls for images only are powers of 2.
3) As you zoom in, fewer requests need to be made since using powers of 2 now.
**Evidence**
=> [bookreader-component] getPageURI fixes

packages/ia-topnav/package.json, packages/ia-topnav/src/lib/query-handler.js
> Top nav Wayback search form doesn't handle encoding correctly. when you enter URL https://whitehouse.gov/ in search field and hit enter, you will be landed on wayback search page but URL shows encoded resulting not result.
Refer to this JIRA: https://webarchive.jira.com/browse/WEBDEV-4189 for more information
=> WEBDEV-4189 Removed extra URL encoding for wayback search component

packages/transcript-view/demo/transcript.js, packages/transcript-view/src/duration-formatter.ts, packages/transcript-view/test/duration-formatter.test.js, packages/transcript-view/test/transcript-view.test.js
> Removes the leading 0 in the duration formatter. ie: 02:13:43 will now be 2:13:43 and 02:43 will be 2:43
**Testing**
> The unit tests cover the new formats
**Evidence**
>
=> [Transcript View] Remove leading 0 in the duration formatter

packages/ia-components/components/audio-players/audio-player-main.jsx, packages/ia-components/components/bookreader-component/bookreader-wrapper-main.jsx, packages/ia-components/components/theatres/with-youtube-spotify/audio-with-youtube-spotify-main.jsx
pass `baseHost` as prop through iaux-music-player so bookreader web component can hook into it
=> iaux player - pass base host through to item-navigator

packages/ia-wayback-search/index.html, packages/ia-wayback-search/src/ia-wayback-search.js
> Clicking on the Wayback Machine logo in the topnav takes you to the wrong url (https://https://archive.org/web/, double `https`).
See here for more information: https://webarchive.jira.com/browse/WEBDEV-4360
**Testing**
=> Wayback Logo URL in topnav

packages/expandable-search-bar/demo/index.html, packages/expandable-search-bar/src/expandable-search-bar.ts
This PR addresses issue #528. The issue was actually broader than described. The expandable search bar was actually unable to use the dropdown options after any user input keystrokes. This PR fixes that and it now works as intended.
**Technical**
The existing code didn't work because it tried to modify a LitElement component from outside the component. LitElement, like similar frameworks, updates the DOM based on changes to state inside components. Also, the previous implementation placed a non-documented obligation on the consumer to know that they must write this supporting code.
This implementation fixes this by changing state from within the component.
I also would like to note that I discovered another pre-existing problem while fixing this, but that goes beyond the …
=> fix expandable search bar issue w/ the dropdown options (quick search)

packages/ia-components/components/audio-players/archive-audio-jwplayer-wrapper.jsx, packages/ia-components/components/pagination/pagination-with-flexbox.jsx, packages/ia-components/components/theatres/with-youtube-spotify/audio-with-youtube-spotify-main.jsx, packages/ia-components/components/track-lists/track-list.jsx, packages/ia-components/components/track-lists/track.jsx, packages/ia-components/package.json
more deterministic check on autoplay.
problem: when jwp changes tracks, the state is `idle`. this metric is not enough to determine if play8 is running autoplay.
solution: check jwp for its current track. if so, then record state to move tracklist's active state.
=> IA jwplayer 8.22 update patch

packages/ia-topnav/index.html, packages/ia-topnav/package-lock.json, packages/ia-topnav/src/dropdown-menu.js, packages/ia-topnav/src/ia-topnav.js, packages/ia-topnav/src/media-menu.js, packages/ia-topnav/src/media-slider.js, packages/ia-topnav/src/search-menu.js, packages/ia-topnav/src/styles/dropdown-menu.js, packages/ia-topnav/src/styles/media-menu.js, packages/ia-topnav/src/styles/media-slider.js, packages/ia-topnav/src/styles/nav-search.js, packages/ia-topnav/src/styles/search-menu.js, packages/ia-topnav/src/user-menu.js, packages/ia-topnav/test/media-menu.test.js
> Currently, when the top nav sliding menus are dismissed, they just slide up, but are still visible above the navigation if you put something above the nav. Now it completely hides the sliding menus when they move out of view.
**Technical**
> It's using overflow: hidden and a height change animation to completely hide the menu when it's not supposed to be visible.
**Testing**
> Resize the browser and open and close menus
**Evidence**
> 
https://user-images.githubusercontent.com/51138/133680793-24d4bf39-4ffa-4fbb-ae69-bc1fdf9a857e.mov
=> Hide menus when they are dismissed

packages/ia-components/.storybook/theatre-styling.less, packages/ia-components/components/data-for-stories/album-78-w-one-image.js, packages/ia-components/components/theatres/with-youtube-spotify/audio-with-youtube-spotify.stories.js, packages/ia-components/components/theatres/with-youtube-spotify/utils/archive-default-album-parser.js, packages/ia-components/components/theatres/with-youtube-spotify/utils/archive-derived-album-parser.js
Adds safety net to use floating/single image as cover for media window
Demo updates
- use list to draw table
- smol table redesign
- new stub for 78 item w/ 1 image
=> liner notes player: use image in item in media window instead of image placeholder

packages/ia-components/components/theatres/with-youtube-spotify/audio-with-youtube-spotify-main.jsx, packages/ia-components/package.json
keeps webamp as player selection.
=> webamp always on

packages/ia-topnav/src/media-slider.js
The `media-slider` component is trying to access the `shadowRoot` before it's ready so now we just skip this update if the `shadowRoot` isn't ready yet.
=> ia-topnav: Check for a shadowRoot before querying it

packages/ia-topnav/src/nav-search.js, packages/ia-topnav/src/search-menu.js
Updates the ia-topnav component to respect the user's opt-in/opt-out preference for the search beta, ensuring that searches from the topnav's search bar go to the correct search page. Also slightly updates the search option labels to match how they are written on the actual search page widget.
**Technical**
Uses the `SearchBeta-opt-in` localStorage key that gets set upon clicking legacy/beta search links.
**Testing**
- For a user in the search beta segment who has opted in by clicking a "Try the new search beta" link, performing a search from the topnav should direct to the beta search page (`/search`).
- For users who either aren't in the search beta, or haven't yet opted into beta search, performing a search from the topnav should direct to the legacy search page …
=> WEBDEV-5525: Direct topnav search to legacy/beta search according to opt-in

packages/ia-topnav/package.json
Bump `ia-topnav` version 1.1.18 -> 1.1.19, with new beta search opt-in changes.
=> ia-topnav@1.1.19

packages/ia-topnav/src/styles/ia-topnav.js, packages/ia-topnav/src/styles/nav-search.js, packages/ia-topnav/src/styles/save-page-form.js
> fixes archive.org non-offshoot-served pages nav form typeins from white-on-white
**Technical**
> seems like rendertron-created CSS causes browser defaults of `color:fieldtext` implicitly relied on rule to not work.  so need to get explicit
**Testing**
> IDK.  dont have spoons to push 3 MRs, npm publish, offshoot package.json version, mr, push, and pi web -- so would like to get this thru from bottom up and i'll get more formal if this fix doesnt work (though it should!) 
**Evidence**
=> fix for rendertron-ed nav input type-in colors

packages/ia-topnav/README.md, packages/ia-topnav/package.json, packages/ia-topnav/src/ia-topnav.js, packages/ia-topnav/src/styles/dropdown-menu.js, packages/ia-topnav/src/styles/search-menu.js
**Some Fixes **
- `--topOffset` now has fallback values
- this helps us remove `display: none;` from primary nav functionality
- ensure `this.screenName` updates when `this.username` updates - so that the nav can dynamically update the displayed screen name.
- readme updates
- package.json prune - remove storybook, remove lerna artifact `gitHead`
=> Topnav updates - `--topOffset` with fallbacks, readme prune, ensure displayed `screenname` updates when `username` updates

packages/ia-topnav/src/media-subnav.js
Remove 10 network requests of images we might not need:
**Technical**
**Testing**
I haven't tested this... should hopefully do the trick, but at worst it'll just be the same as it was before.
**Evidence**
=> Lazy load topnav images

packages/ia-topnav/src/nav-search.js
Updates the `ia-topnav` search bar endpoint to reflect whether the user is included in the launch of the new search, overriding their previous beta opt-in preference. If they are in the launched variant, searches will target the new search page instead of the old one.
**Technical**
Relies on the `SearchBeta-launched` localStorage key being set by offshoot.
**Testing**
**Evidence**
=> [ia-topnav] WEBDEV-5768 Override search beta opt-in status when current user in launch bucket

packages/ia-activity-indicator/src/ia-activity-indicator.js
Fixes a bug where the activity indicator doesn't spin on Safari.
**Technical**
For some reason Safari doesn't infer the end state of `@keyframes` animations when not provided, while all other major browsers do (in accordance with spec). So we need to provide the end frame explicitly for Safari to rotate the spinner.
**Testing**
Run the demo app and open in Safari. Verify that the activity indicator spins continuously. (Current behavior is that it doesn't spin at all)
**Evidence**
> If this PR touches UI, please post evidence (screenshot) of it …
=> Work around Safari bug preventing activity indicator from spinning

packages/ia-topnav/src/data/menus.js, packages/ia-topnav/src/ia-topnav.js
This PR adds admin items to the user menu, which are only displayed when the user has certain edit privileges. This is migrating functionality that exists on petabox-rendered pages, but currently has no Offshoot equivalent.
**Technical**
The admin pages being linked are themselves separately gated behind the appropriate privs -- this PR only impacts the visibility of those links in the topnav.
**Testing**
As a user with privs to edit arbitrary items, visit any collection page and open your user menu in the topnav. There should be an admin …
=> [ia-topnav] WEBDEV-6272 Add admin items to user menu

packages/ia-topnav/package.json
Bump `<ia-topnav>` version to 1.1.27. Version includes admin items in user menu.
=> ia-topnav@1.1.27

packages/ia-userlist-settings/package.json, packages/ia-userlist-settings/yarn.lock
Upgrades `ia-userlist-settings` to `search-service@1.3.0` w/ profile page models, and bumps package version to 1.0.11.
=> ia-userlist-settings@1.0.11

packages/ia-topnav/index.d.ts, packages/ia-topnav/src/data/menus.js, packages/ia-topnav/src/dropdown-menu.js, packages/ia-topnav/src/styles/dropdown-menu.js
Adds a "NEW" callout bubble beside the new "My lists" item on the user menu of the topnav.
**Technical**
Adds a new config value to the topnav, `callouts`, for the parent to specify any callouts that should appear on menu items. This allows Offshoot's app root to specify whether or not the callout should be shown, for instance.
**Testing**
Load the Offshoot review app that includes these topnav changes with the appropriate AB variant override set, and open the user menu. The "My lists" item should be listed, with a "NEW" badge beside it. …
=> [ia-topnav] WEBDEV-6698 Add user menu callout on My Lists item

packages/ia-topnav/package.json
Bumps ia-topnav version to 1.1.35
=> Bump `ia-topnav` to v1.1.35

packages/ia-topnav/src/dropdown-menu.js
Currently the `aria-label` for callouts is being erroneously applied to every item in the user menu. This PR adds the intended condition so that it only appears on called-out items.
=> WEBDEV-6727 Only include 'New feature' label when callout is present

packages/ia-topnav/package.json
Version includes bugfix for "New feature" callout aria-label being applied in places where it shouldn't.
=> Bump ia-topnav version to 1.1.36

packages/ia-topnav/src/media-menu.js, packages/ia-topnav/src/wayback-slider.js, packages/ia-wayback-search/README.md, packages/ia-wayback-search/index.html, packages/ia-wayback-search/src/ia-wayback-search.js, packages/ia-wayback-search/test/wayback-search.test.js
Update WB link
relates to https://webarchive.jira.com/browse/WEBDEV-6584
very simple
check the nav
wayback links in the nav should be web.archive.org
=> wayback home is moving from petabox to web.archive.org

packages/ia-topnav/package.json
Version includes fixes for search menu dropdown should dismiss when click outside:
https://webarchive.jira.com/browse/WEBDEV-6739
=> ia-topnav bump to 1.1.37

packages/ia-topnav/src/nav-search.js
Converts old references to the `/search.php` endpoint to `/search`, so that searches are sent directly to the newer page without an extra redirect. Also eliminates a related obsolete flag for the search beta opt-in, which is no longer required.
=> [ia-topnav] WEBDEV-6909 Remove old references to search.php (now /search) and obsolete beta flag

packages/ia-topnav/package.json
Version includes fixes to search endpoint for inclusion of radio searches within Offshoot.
=> Bump ia-topnav to v1.3.6

packages/ia-userlist-settings/package.json
Version bump to prep for federated search carousel merge.
=> Bump ia-userlist-settings to v1.0.21

packages/ia-topnav/src/data/menus.js
Switches the top-nav URLs to `/about` pages to point to the new links created for the Offshoot versions of these pages, i.e. `/jobs.php` > `/jobs`, `/volunteerpositions.php` > `/volunteer-positions`
=> WEBDEV-7139 Switch top nav URLs to new about pages

packages/ia-topnav/package.json
Updates topnav to new version to integrate changes from [WEBDEV-7139](https://webarchive.jira.com/browse/WEBDEV-7139) -- links now point to new `/about/` URLs. Skips from `1.3.6` > `1.3.8` because `1.3.7` had already been npm-published and used by Offshoot, just not merged.
[WEBDEV-7139]: https://webarchive.jira.com/browse/WEBDEV-7139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> topnav v1.3.8

packages/ia-activity-indicator/package-lock.json, packages/ia-activity-indicator/package.json
Simple version update to our new standard `1.0.0` starting point
=> WEBDEV-7504 Update ia-activity-indicator to version 1.0.0
