internetarchive/iaux

- README.md
Instead of integration, there is 'intergration'
Closes #
> **Evidence**: If this PR touches UI, please post evidence (screenshot) of it behaving correctly:
> Typo: in ia-component section

- packages/ia-components/sandbox/pagination/pagination-with-flexbox.jsx
Closes #59 
> **Evidence**: If this PR touches UI, please post evidence (screenshot) of it behaving correctly:
> Adds React key prop to page buttons in pagination

- packages/ia-components/sandbox/theatres/components/audio-player/audio-player-main.jsx
- packages/ia-components/sandbox/theatres/components/audio-player/audio-player.less
- packages/ia-components/sandbox/theatres/components/audio-player/players_by_type/archive-audio-jwplayer-wrapper.jsx
- packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify.less
- packages/ia-components/variables.less
Music Player - show warning text when user is playing 3rd party player for the first time
WEBDEV-2066
Music Player - update pagination height
part of WEBDEV-2056
> Music Player: show ad blocker warning text & ensure the theatre does not grow the details theatre

- packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify.less
- packages/ia-components/variables.less
Fixed issues:
1) does not cover peek-a-boo title in details page of archive.org
2) does not change size when switching channels
WEBDEV-2056
> Music Player: fix track list height issues 

- packages/ia-components/sandbox/IAReactComponent.js
- packages/ia-components/sandbox/tiles/ParentTileImg.js
- packages/ia-components/sandbox/tiles/TileComponent.js
- packages/ia-components/sandbox/tiles/TileImage.js
Closes #
> **Evidence**: If this PR touches UI, please post evidence (screenshot) of it behaving correctly:
> Add tiles components and IAReactComponent from dweb-archive

- packages/ia-components/sandbox/pagination/pagination-with-flexbox.jsx
- packages/ia-components/sandbox/theatres/components/track-list/track-list.jsx
- packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify-main.jsx
- packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify.less
Pagination:
- make sure that we find the item in view and that the controls reflect the page it is in
Music Player:
- If third party channel does not have the track, then set it to track 1
Current code is for QA here: https://www-isa.archive.org/details/cd_the-essential-willie-nelson_willie-nelson-aerosmith-emmylou-harris-jul
> Music Player updates around Pagination, and setting default track

- packages/ia-components/sandbox/pagination/pagination-with-flexbox.jsx
- packages/ia-components/sandbox/pagination/pagination.less
- packages/ia-components/sandbox/pagination/utils/dom-dimensions.js
- packages/ia-components/sandbox/theatres/components/audio-player/audio-player.less
- packages/ia-components/sandbox/theatres/components/track-list/track-list.jsx
- packages/ia-components/sandbox/theatres/components/track-list/track-list.less
- packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify-main.jsx
- packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify.less
- packages/ia-components/variables.less
- update view on desktop media query
- make sure selected track border does not creep into another page's view
- add resize event handler, recalculate dimensions accordingly
- remove unused functions, cleanup
> Pagination & Music track list - adapt on window resize

- packages/ia-components/sandbox/theatres/components/audio-player/audio-player-main.jsx
- packages/ia-components/sandbox/theatres/components/audio-player/audio-player.less
- packages/ia-components/sandbox/theatres/components/audio-player/audio-player.test.js
- packages/ia-components/sandbox/theatres/components/track-list/track-list.jsx
- packages/ia-components/sandbox/theatres/components/track-list/track-list.test.js
Add fallback cases for music player - no background photo, no tracks + unit tests
> Add fallback cases for music player - no background photo, no tracks

- README.md
- packages/ia-prototype-apps/README.md
- Fixes commands in README.md
- Remove extra lines in README.md
n/a
n/a
> **Evidence**: If this PR touches UI, please post evidence (screenshot) of it behaving correctly:
> Fix commands for running prototype

- packages/ia-js-client/src/controllers/item/item.ts
- packages/ia-js-client/src/services/related.ts
After this fix,all packages installed succesffully..
**Evidence**
> Fixed setup errors due to typo in related.ts and item.ts(issue #108)

- packages/ia-components/sandbox/pagination/pagination-with-flexbox.jsx
- packages/ia-components/sandbox/theatres/components/audio-player/players_by_type/archive-audio-jwplayer-wrapper.jsx
- packages/ia-components/sandbox/theatres/components/track-list/track-list.jsx
1) Track list: ensure track number 0 is handled
2) Pagination: add guard around focusing on selected item
3) JWPlayer: hiding code to change url until ready for full support
> Music Player guards

- packages/ia-components/sandbox/tiles/TileComponent.js
- packages/ia-components/util.js
Creates a basic util.js. in ia-components, where small functions used in multiple places can be put. 
**Technical**
I've gone for one-file, multiple exports, as I think its clearer to say exactly what functions are used anywhere. 
**Testing**
No way to test on IAUX presently
> Added util file to ia-components as discussed and moved some functions to it

- packages/ia-components/sandbox/theatres/components/audio-player/players_by_type/archive-audio-jwplayer-wrapper.jsx
UX Problem:
The user cannot select highlighted track on track list to start playing track when player doesn't start on first track.
Technical Problem:
This regression was introduced when Play8.js was updated to handle new browser issues that affected overal UX.
This meant that the initial load of Play8 with JWPlayer has changed from 1 to 2 callback emits. This is a known count across browsers.
Technical Solution:
- Add the notion of when JWPlayer load has stabilized when player starts at N (where N > track 1).  This needs:
- manual counts of how many times JWPlayer fires `onPlaylistItem` event on load
- manual checks when state updates in `shouldComponentUpdate` and `componentDidUpdate`
- manual calls to global jwplayer outside of Play8 wrapper
This update did not affect what currently …
> Music Player, JWPlayer wrapper: manually play the track that the player starts on

- packages/ia-design-system/src/styles/utils.less
Adds a Less mixin for the `appearance` property.
**Technical**
Accepts one required argument, the value of the property.
**Testing**
To be completed in Petabox with ticket WEBDEV-2221.
**Evidence**
N/A
> Adds appearance Less mixin

- packages/ia-components/package.json
- packages/ia-components/yarn.lock
- yarn.lock
Does what it says on the tin.
Closes #174 
**Technical**
Minor version bump, so no API changes worth noting.
**Testing**
Run storybook within ia-components, click theaters -> Audio with YouTube, Spotify, then click "bestofdollyparto00part" in Supported Items. The album displayed should be updated.
> Upgrades Axios in ia-components

- packages/ia-components/sandbox/theatres/components/track-list/track-list.stories.js
> What does this PR achieve?
User interface story for the only tracklist.
> Track List story

- package.json
- packages/ia-prototype-apps/package.json
- packages/ia-prototype-apps/yarn.lock
- yarn.lock
> Upgrades parcel bundler to address security alert

- packages/ia-components/dweb-index.js
- packages/ia-components/index.js
creates new dweb index.
Closes #205
> Creating DWEB index file

- packages/ia-components/package.json
> Upgrades bookreader

- packages/ia-components/sandbox/bookreader-component/bookreader-wrapper-main.jsx
Closes WEBDEV-2354 and #215`.
**Technical**
Add option to do scaling when creating image URL
**Testing**
https://www-markcarranza6.archive.org/details/bestofdollyparto00part
**Evidence**
> Add option to scale bookreader images

- packages/ia-components/sandbox/audio-players/youtube-player.jsx
- packages/ia-components/sandbox/theatres/with-youtube-spotify/audio-with-youtube-spotify-main.jsx
Fixes the following UI Symptoms:
- page load > channel change to YouTube > user clicks on selected track, the video doesn't play
> Updates to YouTube Wrapper Behavior

- packages/ia-components/integration/audio_player.test.js
- packages/ia-components/integration/example.test.js
- packages/ia-components/integration/jest.config.js
- packages/ia-components/integration/jestConfigAfterEnv.js
- packages/ia-components/integration/utils/traversal.js
- packages/ia-components/package.json
- packages/ia-components/yarn.lock
Closes #266.
**Technical**
Because Storybook renders components in an iframe, each test needs to start by switching the driver context to the iframe contentDocument. This and a few other heavily used methods are abstracted for use across future integration tests.
**Testing**
• `cd packages/ia-components && yarn run storybook`
• `cd packages/ia-components && yarn run test:integration`
**Evidence**
> Adds music player tests

- topnav/assets/img/ia-user-999.svg
- topnav/assets/img/ia-user-fff.svg
- topnav/topnav-element.js
- topnav/user-menu.js
Adds user menu to the navigation bar.
Closes #255
**Technical**
To view navbar
`npm install`
`npm install -g polymer-cli`
`cd topnav && polymer serve`
**Testing**
Open/close usermenu and compare behaviour as displayed in prototype (#247)
**Possible additions**
1. Replacing focus ring with change in the background colour of the focused element
**Additions to be made later**
1. Closing user menu when content is clicked
2. Closing user menu when another button is clicked
> Implement user menu

- packages/scrubber-bar/demo/index.html
- packages/scrubber-bar/index.d.ts
- packages/scrubber-bar/package.json
- packages/scrubber-bar/scrubber-bar.js
- packages/scrubber-bar/src/scrubber-bar.ts
- packages/scrubber-bar/stories/index.stories.js
- packages/scrubber-bar/test/scrubber-bar.test.js
> This adds a declarations file so other TypeScript projects can easily import the Scrubber Bar, as well as cleaning up some imports
**Technical**
> This is mostly some TypeScript updates like the declarations file
**Testing**
> Check out the `scrubber-bar-updates` branch of the repo, `lerna link`, `lerna bootstrap`, `cd packages/scrubber-bar`, `yarn start` and you can play with the scrubber view. `yarn test` to run the tests.
**Evidence**
> No UI updates
> Scrubber Bar: Add TypeScript declarations file and update imports

- packages/playback-controls/demo/index.html
- packages/playback-controls/index.d.ts
- packages/playback-controls/index.js
- packages/playback-controls/package.json
- packages/playback-controls/playback-controls.js
- packages/playback-controls/src/assets/img/playback-speed.ts
- packages/playback-controls/src/assets/img/volume/volume-full.ts
- packages/playback-controls/src/assets/img/volume/volume-medium.ts
- packages/playback-controls/src/assets/img/volume/volume-mute.ts
- packages/playback-controls/src/playback-controls.ts
- packages/playback-controls/stories/index.stories.js
- packages/playback-controls/test/playback-controls.test.js
> Adds playback speed, volume control, and add TypeScript declarations
**Technical**
> This adds a TypeScript declarations file so other TS projects can easily consume it
**Testing**
> Check out the `playback-controls-updates` branch of the repo, `lerna link`, `lerna bootstrap`, `cd packages/playback-controls`, `yarn start` and you can play with the playback controls.
> Run `yarn test` to run the unit tests.
**Evidence**
>
> Playback Controls: Playback Speed, Volume, TypeScript Updates

- packages/waveform-progress/index.d.ts
- packages/waveform-progress/index.js
- packages/waveform-progress/package.json
- packages/waveform-progress/src/waveform-progress.ts
- packages/waveform-progress/stories/index.stories.js
- packages/waveform-progress/test/waveform-progress.test.js
- packages/waveform-progress/tsconfig.json
- packages/waveform-progress/waveform-progress.js
> Update some TypeScript things like the declarations file for other TS consumers
**Technical**
> Mostly just TS updates.
**Testing**
> Check out the `waveform-progress-updates` branch of the repo, `cd packages/waveform-progress`, `yarn start` and you can play with the Waveform Progress Bar.
> Run `yarn test` to run the unit tests.
**Evidence**
> No real UI updates, just a default color change
> Waveform Progress: Update some configurations to help with TypeScript support

- packages/audio-element/package.json
- packages/playback-controls/package.json
- packages/scrubber-bar/package.json
- packages/transcript-view/package.json
- packages/waveform-progress/package.json
> Lerna bumped the versions of these packages, but I want to start on 0.0.0
**Technical**
> n/a
**Testing**
> n/a
**Evidence**
> n/a
> Radio Player: Reset Component Version Numbers

- packages/audio-element/README.md
- packages/audio-element/package.json
- packages/playback-controls/README.md
- packages/playback-controls/package.json
- packages/scrubber-bar/README.md
- packages/scrubber-bar/package.json
- packages/transcript-view/README.md
- packages/transcript-view/package.json
- packages/waveform-progress/README.md
- packages/waveform-progress/package.json
> Adds `files` entry to `package.json` to limit what is published to NPM
**Technical**
> We don't want the entire package published to NPM, mainly just the `lib` directory and the entry points like `index.js` and `index.d.ts`.
**Testing**
> n/a
**Evidence**
> n/a
> Update NPM Packaging

- README.md
I tried going to Lerna's page to learn about it for contributions, but link was dead.
Homepage I found is https://lerna.js.org.
**Technical**
**Testing**
**Evidence**
> Dead link: in Overview section

- packages/ia-components/sandbox/audio-players/archive-audio-jwplayer-wrapper.jsx
- packages/ia-components/sandbox/audio-players/audio-player-main.jsx
- packages/ia-components/sandbox/audio-players/audio-player.test.js
- packages/ia-components/sandbox/selectors/horizontal-radio-group/horizontal-radio-group.jsx
- packages/ia-components/sandbox/selectors/horizontal-radio-group/horizontal-radio-group.test.js
- packages/ia-components/sandbox/theatres/with-youtube-spotify/utils/flatten-album-data.test.js
- packages/ia-components/sandbox/track-lists/track-list.jsx
- packages/ia-components/sandbox/track-lists/track-list.test.js
Clean up unit tests & their component counterparts
**Testing**
run `yarn run test`
- unit tests pass
(not counting selenium)
**Evidence**
> Test cleanup

- packages/transcript-view/demo/index.html
- packages/transcript-view/demo/transcript.js
- packages/transcript-view/dev_tools/search-results-switcher.ts
- packages/transcript-view/dev_tools/transcript-view-dev-options.ts
- packages/transcript-view/package.json
- packages/transcript-view/src/duration-formatter.ts
- packages/transcript-view/src/models/transcript-config.ts
- packages/transcript-view/src/models/transcript-entry-config.ts
- packages/transcript-view/src/transcript-entry.ts
- packages/transcript-view/src/transcript-view.ts
- packages/transcript-view/test/transcript-config.test.js
- packages/transcript-view/test/transcript-entry-config.test.js
- packages/transcript-view/test/transcript-entry.test.js
- packages/transcript-view/test/transcript-view.test.js
> This updates some of the user interactions with the transcript view as well as adds several styling variables so the consumer can style it better.
**Technical**
> n/a
**Testing**
> Run `yarn install`, `yarn test` to run tests. Run `yarn start` to play with it in the browser
**Evidence**
> n/a
> Transcript View: Update Interaction and Configurability

- packages/waveform-progress/.eslintrc
- packages/waveform-progress/package.json
- packages/waveform-progress/src/waveform-progress.ts
- packages/waveform-progress/test/waveform-progress.test.js
> Fix tests and linting in the Waveform Progress component
**Technical**
> n/a
**Testing**
> Run `yarn install`, `yarn test` to run tests. Run `yarn start` to see it in the browser.
**Evidence**
> n/a
> Waveform Progress Fixes and Linting

- .travis.yml
- README.md
- packages/ia-components/integration/audio_player.test.js
- packages/ia-components/integration/example.test.js
- packages/ia-components/package.json
- packages/ia-components/yarn.lock
- packages/radio-player/test/radio-player.test.js
> Fix failing tests in ia-components
**Technical**
> We weren't running the storybook server when running the tests so they were all failing right off the bat.
**Testing**
> Check out this branch, run yarn bootstrap in `packages/ia-components`. Then run `yarn test`
**Evidence**
> n/a
> Fix `ia-component` Tests

- packages/ia-components/sandbox/language-select/index.stories.js
- packages/ia-components/sandbox/language-select/language-select.js
- packages/ia-components/sandbox/language-select/language-select.less
- packages/ia-components/sandbox/language-select/language-select.stories.js
- packages/ia-components/sandbox/language-select/language-select.test.js
Closes #378
**Technical**
Sandbox component added to Storybook. Run Storybook using the README instructions to test implementation.
**Testing**
Interact with rendered component in Storybook. Run `yarn test` within packages/ia-components to run unit tests.
**Evidence**
> Creates language select component

- packages/ia-components/sandbox/language-select/index.stories.js
Removing artifact from removing dweb language selector
> remove rebase artifact

- .travis.yml
> Push Travis build notifications to Slack
> Add Travis Notifications to Slack

- .travis.yml
Testing exclusion of Slack notification step from TravisCI.
> Excludes Slack notification for forks

- packages/example-webcomponent/yarn.lock
Fixes TravisCI failure related to missing package
> Rebuild example-webcomponent package.lock

- packages/mobile-top-nav/package.json
- packages/mobile-top-nav/src/user-menu.js
Fixes user menu peeking in mobile viewports in landscape orientation.
> Sets hard pixel offset to ensure user menu offscren

- packages/ia-topnav/package.json
New release of ia-topnav
* `config.hideSearch` boolean added to toggle visibility of search menu button and search form
> Releases ia-topnav 0.2.3

- packages/ia-topnav/package.json
- packages/ia-topnav/src/login-button.js
- packages/ia-topnav/src/styles/primary-nav.js
See https://webarchive.jira.com/browse/WEBDEV-3406
> WEBDEV-3406: style changes

- packages/ia-topnav/package.json
- packages/ia-topnav/src/styles/login-button.js
- packages/ia-topnav/src/styles/primary-nav.js
- packages/ia-topnav/src/styles/signed-out-dropdown.js
- packages/ia-topnav/src/styles/user-menu.js
Fixes remaining issues in https://webarchive.jira.com/browse/WEBDEV-3406
**Testing**
https://www-shaner.archive.org/
> Adjusts styles to address design QA

- packages/audio-element/package.json
- packages/expandable-search-bar/package.json
- packages/ia-activity-indicator/package.json
- packages/playback-controls/package.json
- packages/radio-player/package.json
- packages/radio-player/test/search-handler/search-helper.test.js
- packages/radio-player/test/search-handler/search-model.test.js
- packages/radio-player/yarn.lock
- packages/scrubber-bar/package.json
- packages/transcript-view/package.json
- packages/waveform-progress/package.json
We were using canary versions so this starts to formalize the development a bit more.
> Update Versions of Radio Player Components to 0.0.1

- packages/mobile-top-nav/package.json
- packages/mobile-top-nav/src/search-menu.js
> Uses fixed measurement to position closed search menu

- packages/ia-topnav/package.json
- packages/ia-topnav/src/data/menus.js
- packages/mobile-top-nav/package.json
- packages/mobile-top-nav/src/data/menus.js
> Removes default sort from "books to borrow" nav link

- packages/ia-topnav/package.json
- packages/ia-topnav/src/data/menus.js
- packages/ia-topnav/src/media-subnav.js
Fixes (WEBDEV-3550)[https://webarchive.jira.com/browse/WEBDEV-3550]
> Fixes text of software nav item

- packages/ia-topnav/README.md
- packages/ia-topnav/base64_encoded_menus.html
- packages/ia-topnav/index.html
- packages/ia-topnav/package.json
- packages/ia-topnav/src/data/menus.js
- packages/ia-topnav/src/data/petabox_signedout_menus.js
- packages/ia-topnav/src/desktop-subnav.js
- packages/ia-topnav/src/dropdown-menu.js
- packages/ia-topnav/src/ia-topnav.js
- packages/ia-topnav/src/media-slider.js
- packages/ia-topnav/src/media-subnav.js
- packages/ia-topnav/src/more-slider.js
- packages/ia-topnav/test/data/menus.test.js
- packages/ia-topnav/test/media-slider.test.js
- packages/ia-topnav/test/more-slider.test.js
Moves the menu arrays and objects out of ia-topnav and instead accepts a prop `menus` that internally sends individual menus to the concerned components. This will be necessary for v1, as I will be removing the current static nav from Nav.inc and passing the generated menu objects to ia-topnav on render.
> Receives menu objects from external data

- packages/ia-topnav/index.html
- packages/ia-topnav/package.json
- packages/ia-topnav/src/ia-topnav.js
- packages/ia-topnav/test/ia-topnav.test.js
> Fixes a bug in mobile view where the Sign Up and Log In buttons went to an incorrect URL
**Technical**
> We weren't passing the baseHost into the signed out dropdown
> Fix TopNav Signed Out Bug

- packages/ia-topnav/src/media-button.js
- packages/ia-topnav/src/primary-nav.js
https://webarchive.jira.com/browse/WEBDEV-3856
> Added title attribute on media button in topnav so whenever user mouse over, it will say "Expand texts/video/audio menu".
> Added expand title on topnav media buttons

- packages/ia-components/sandbox/bookreader-component/bookreader-wrapper-main.jsx
Added some BR configuration for liner notes
> New BR changes for liner notes configuration

- .github/workflows/node.js.yml
**Technical**
**Testing**
**Evidence**
> Using node_modules caching to speed up GitHub Action

- packages/ia-components/package.json
They're currently timing out and need some investigation
> WIP: Disable ia-components tests

- packages/ia-components/.storybook/main.js
- packages/ia-components/.storybook/preview-head.html
- packages/ia-components/components/audio-players/audio-player-main.jsx
- packages/ia-components/components/audio-players/audio-player.less
- packages/ia-components/components/bookreader-component/README.md
- packages/ia-components/components/bookreader-component/bookreader-wrapper-main.jsx
- packages/ia-components/components/theatres/with-youtube-spotify/audio-with-youtube-spotify-main.jsx
- packages/ia-components/components/theatres/with-youtube-spotify/audio-with-youtube-spotify.less
- packages/ia-components/components/theatres/with-youtube-spotify/audio-with-youtube-spotify.stories.js
- packages/ia-components/package.json
- packages/ia-components/yarn.lock
Updates IA BookReader DOM to use web component
**Technical**
- storybook pulls in latest script tags that will activate the web component
**Testing**
- pull down branch -> go to: /packages/ia-components
- open `~/.storybook/preview-head.html` and point scripts to `www-isa2.archive.org` instead of `archive.org` to fetch latest bookreader & archive.org changes
- `yarn install && yarn run storybook`
- storybook runs -> go to theater demos -> "Audio with liner notes"
- toggle `Liner Notes` tab -> BookReader with new side panels are now being used
- toggle fullscreen -> bookreader toggles in & out of fullscreen
**Evidence**
bookreader shows liner notes in storybook demo & on [staging app](https://www-isa2.archive.org/details/cd_hanna-barbera-cartoon-sound-fx_william-hanna-joseph …
> Audio player with liner notes: use BookReader v5

- packages/ia-topnav/README.md
- packages/ia-topnav/index.d.ts
- packages/ia-topnav/index.html
- packages/ia-topnav/package.json
- packages/ia-topnav/src/desktop-subnav.js
- packages/ia-topnav/src/dropdown-menu.js
- packages/ia-topnav/src/ia-topnav.js
- packages/ia-topnav/src/nav-search.js
- packages/ia-topnav/src/primary-nav.js
- packages/ia-topnav/src/search-menu.js
- packages/ia-topnav/src/user-menu.js
- packages/ia-topnav/test/ia-topnav.test.js
- packages/ia-topnav/test/nav-search.test.js
- packages/ia-topnav/test/primary-nav.test.js
> Update IA Top Nav configuration to better support single-page-apps
**Technical**
> This moves several of the `config` parameters into their own reactive properties so we can control without having to rebuild the entire config each time.
**Testing**
> Testing notes in JIRA ticket
> TopNav Offshoot Updates

- packages/ia-topnav/index.d.ts
- packages/ia-topnav/src/ia-topnav.js
Add missing typescript definitions for TopNav
> Add missing typescript definitions to ia-topnav

- packages/expandable-search-bar/README.md
- packages/expandable-search-bar/package.json
- packages/expandable-search-bar/yarn.lock
> Removes `storybook` from `expandable-search-bar` 
fix #574 
`Closes #574`.
**Technical**
> Storybooks scripts removed from `package.json` and `README`.
> Fix #574 Removed storybooks from expandable-search-bar

- packages/expandable-search-bar/README.md
- packages/expandable-search-bar/package.json
- packages/expandable-search-bar/yarn.lock
>Fix #573 
**Technical**
> Storybooks removed from `scrubber-bar-package`
> Removed storybook from `scrubber-bar package`

- packages/ia-topnav/package.json
- packages/ia-topnav/src/ia-topnav.js
- packages/ia-topnav/src/styles/signed-out-dropdown.js
https://webarchive.jira.com/browse/WEBDEV-4557
> WEBDEV-4557 - Fix guest user dropdown position when there is no search bar in topnav

- packages/ia-topnav/base64_encoded_menus.html
- packages/ia-topnav/index.d.ts
- packages/ia-topnav/index.html
- packages/ia-topnav/src/data/menus.js
- packages/ia-topnav/src/styles/dropdown-menu.js
- packages/ia-topnav/src/styles/media-slider.js
- packages/ia-topnav/src/styles/search-menu.js
Update Typescript declarations with some new attributes and fix some existing menu options. There were also some z-index issues when the menu was supposed to be floating over other elements on screen.
> Offshoot Topnav Updates

- packages/ia-activity-indicator/demo/index.html
- packages/ia-activity-indicator/package.json
- packages/ia-activity-indicator/src/ia-activity-indicator.js
- packages/ia-activity-indicator/yarn.lock
Update Activity Indicator to Lit2
> WEBDEV-4858: Update Activity Indicator to Lit2

- packages/ia-components/components/audio-players/archive-audio-jwplayer-wrapper.jsx
- packages/ia-components/components/bookreader-component/bookreader-wrapper-main.jsx
- packages/ia-components/yarn.lock
**Bookreader property update**
- move `signedIn` to be set via JS bc `<ia-bookreader>` does not treat `signedIn` as an attribute.  This means setting `signedIn` as attr always returns true.
**Update dependencies**
- update storybook
- update <ia-bookreader>
**Autoplay fix:**
- JWP does not fire a `playlistItem` call when starting on cold load.
The React player, during update cycle, it thinks that it should fire a `playN` when it autoplays to next track after starting on cold load.  This innundate's JWP's "play" cycle and causes a stalemate, not playing the next track.
Current Solution:
- move notion of "autoplay" higher up the chain in `componentDidUpdate` cycle so that it can be checked when React player does its initial confirmation that player is ready.  [review …
> Liner notes player - check autoplay during cold load + move <ia-br> `signedin` property out of attr + update deps

- packages/ia-topnav/src/data/menus.js
- packages/ia-topnav/src/data/petabox_signedout_menus.js
- change Wayback Chrome extension link
- add Wayback Edge extension link
> Change topnav browser extension Chrome link and add Edge link

- packages/transcript-view/.eslintrc
- packages/transcript-view/dev_tools/search-results-switcher.ts
- packages/transcript-view/dev_tools/transcript-view-dev-options.ts
- packages/transcript-view/package.json
- packages/transcript-view/src/duration-formatter.ts
- packages/transcript-view/src/transcript-entry.ts
- packages/transcript-view/src/transcript-view.ts
- packages/transcript-view/yarn.lock
> Lit2 radio components transcript view

- packages/playback-controls/.eslintrc
- packages/playback-controls/package.json
- packages/playback-controls/src/assets/img/next-section.ts
- packages/playback-controls/src/assets/img/pause.ts
- packages/playback-controls/src/assets/img/play.ts
- packages/playback-controls/src/assets/img/playback-speed.ts
- packages/playback-controls/src/assets/img/previous-section.ts
- packages/playback-controls/src/assets/img/replay.ts
- packages/playback-controls/src/assets/img/skip-ahead.ts
- packages/playback-controls/src/assets/img/volume/volume-full.ts
- packages/playback-controls/src/assets/img/volume/volume-medium.ts
- packages/playback-controls/src/assets/img/volume/volume-mute.ts
- packages/playback-controls/src/playback-controls.ts
- packages/playback-controls/yarn.lock
> radio player: playback controls lit2 update + eslint fixes

- packages/scrubber-bar/.eslintrc
- packages/scrubber-bar/demo/index.html
- packages/scrubber-bar/package.json
- packages/scrubber-bar/src/assets/img/next-section-marker.ts
- packages/scrubber-bar/src/assets/img/previous-section-marker.ts
- packages/scrubber-bar/src/scrubber-bar.ts
- packages/scrubber-bar/src/section-marker.ts
- packages/scrubber-bar/yarn.lock
> radio player, scrubber bar: lit 2 + eslint upgrades

- packages/ia-components/components/audio-players/audio-player.scss
- packages/ia-components/components/audio-players/youtube-player.scss
- packages/ia-components/components/language-select/language-select.scss
- packages/ia-components/components/pagination/pagination.scss
- packages/ia-components/components/selectors/horizontal-radio-group/horizontal-radio-group.scss
- packages/ia-components/components/theatres/with-youtube-spotify/audio-with-youtube-spotify.scss
- packages/ia-components/components/track-lists/track-list.scss
- packages/ia-components/index.scss
- packages/ia-components/variables.scss
…S.  made via: `cd packages/ia-components &&  npx less2scss -r -s . -d .`
SCSS equivalents of LESS files, as petabox is likely migrating to SASS
made via: `cd packages/ia-components && npx less2scss -r -s . -d .`
**Technical**
**Testing**
**Evidence**
> SCSS equivalents of LESS files, as petabox is likely migrating to SASS

- packages/ia-components/components/theatres/with-youtube-spotify/audio-with-youtube-spotify.scss
bugfix
**Technical**
simple var interpolation fix
**Testing**
https://www-tracey2.archive.org/details/cd_televisions-greatest-hits-volume-3-70s-80_various-artists-al-burton-alan-thicke-ally_0
**Evidence**
https://www-tracey2.archive.org/details/cd_televisions-greatest-hits-volume-3-70s-80_various-artists-al-burton-alan-thicke-ally_0
> whups, didnt notice the `calc()` calls that `npx less2scss` slightly mangled

- packages/ia-topnav/package.json
- packages/ia-topnav/src/styles/search-menu.js
> `Closes WEBDEV-5703`.
**Technical**
> updated CSS var `--topOffset` value
**Testing**
> see WEBDEV-5703
**Evidence**
> see WEBDEV-5703
> Fix search-menu overlapped with donation banner in offshoot

- README.md
- package.json
- yarn.lock
Clearing old and invalid context of iaux repo.
> update readme to note each package is independent + remove unused lerna

- packages/ia-topnav/package.json
Updates ia-topnav version to 1.1.23
> ia-topnav@1.1.23

- packages/ia-activity-indicator/package-lock.json
- packages/ia-activity-indicator/package.json
- packages/ia-activity-indicator/yarn.lock
Upgrades `ia-activity-indicator` package to v0.0.4, with fix for non-spinning Safari bug.
> `ia-activity-indicator` @ 0.0.4

- packages/ia-topnav/package.json
- packages/ia-topnav/src/ia-topnav.js
https://webarchive.jira.com/browse/WEBDEV-6330
> Suppress admin links in topnav on homepage and search page

- packages/ia-userlist-settings/package.json
Bumps `ia-userlist-settings` to v1.0.5
> ia-userlist-settings@1.0.5

- packages/ia-userlist-settings/package.json
Bumps `ia-userlist-settings` version to 1.0.7
> Bump ia-userlist-settings to v1.0.7

- packages/ia-userlist-settings/index.ts
- packages/ia-userlist-settings/src/ia-user-list-settings.ts
- packages/ia-userlist-settings/src/user-lists-service/user-lists-error.ts
- packages/ia-userlist-settings/src/user-lists-service/user-lists-service-interface.ts
- packages/ia-userlist-settings/src/user-lists-service/user-lists-service.ts
There is no manual changes. all the changes are because of `yarn run format`
> Fixed eslint issues on ia-userlist-settings

- packages/ia-topnav/package.json
- packages/ia-topnav/src/ia-topnav.js
- packages/ia-topnav/src/primary-nav.js
- packages/ia-topnav/src/styles/primary-nav.js
- packages/ia-topnav/yarn.lock
- www/ia-topnav/index.html
WEBDEV-5735
- Uses screen name for user icon `alt=` and user string in top nav 
- Uses in-browser truncation
- Fixed and added screen name truncation tests to demo
- Handles RTL language screen names 
**Technical**
- in-code string truncation removed
**Testing**
- Try to break truncation of unicode using multi-code point characters (ex. family with kids) and lengthening `max-width` in browser inspector.
- Try to break with XSS screen names
- QA: Is the `max-width` the right width?
**Evidence**
> Use screen name in Topnav, unicode truncate in-browser

- packages/ia-topnav/src/primary-nav.js
- packages/ia-topnav/src/styles/primary-nav.js
- www/ia-topnav/index.html
Approach:
- use <nav>'s mobile css grid to add heart
- + toggle `<nav>` css grid's area when hiding search icon
- + update nearby css values from rem to px since they aren't fonts
> Webdev-6525 donation heart mobile

- packages/ia-userlist-settings/src/ia-user-list-settings.ts
- packages/ia-userlist-settings/src/user-lists-service/user-lists-service-interface.ts
- packages/ia-userlist-settings/src/user-lists-service/user-lists-service.ts
- packages/ia-userlist-settings/test/ia-user-list-settings.test.ts
Invalid return type when list member is removed.
Referenced to https://webarchive.jira.com/browse/WEBDEV-6680
> Fixing return type when remove members from list

- packages/ia-userlist-settings/package.json
Fixing return type when remove members from list #891 - @nsharma123
> ia-userlist-settings@1.0.13

- packages/ia-userlist-settings/package.json
- packages/ia-userlist-settings/yarn.lock
Includes upgrade to search-service v1.3.2
> Bump ia-userlist-settings to v1.0.17

- packages/ia-topnav/package.json
https://webarchive.jira.com/browse/WEBDEV-6587
> Ia topnav@1.3.0

- packages/ia-userlist-settings/package.json
https://webarchive.jira.com/browse/WEBDEV-6830
> Version bump for ia-userlist-settings component

- packages/ia-topnav/package.json
This version is belongs to ticket https://webarchive.jira.com/browse/WEBDEV-6784 with following pull requests
#908 topnav unit conversion @nsharma123 
#909 ia-wayback-search header icon changes @nsharma123
> ia-topnav v1.3.2

- packages/ia-topnav/package.json
Fixed: Revert className changes which leads more petabox change #911 @nsharma123
> ia-topnav v1.3.4

- packages/ia-topnav/package.json
- packages/ia-topnav/src/data/menus.js
- packages/ia-topnav/src/media-menu.js
Updates the top nav link for books and its sub-pane contents
**Testing**
See JIRA WEBDEV-7011
> Update Books nav link and pane

- packages/ia-userlist-settings/package.json
- packages/ia-userlist-settings/yarn.lock
Version includes updated search service version for WEBDEV-6909.
> Bump ia-userlist-settings to v1.0.20

- packages/ia-userlist-settings/package.json
- packages/ia-userlist-settings/yarn.lock
Updates search service version to avoid type errors in Offshoot following federated search addition.
> Update ia-userlist-settings to new search service

- packages/ia-userlist-settings/package.json
- packages/ia-userlist-settings/src/user-lists-service/user-lists-service.ts
- packages/ia-userlist-settings/yarn.lock
Bump ia-userlist-settings version to 1.0.22 and modal-manager dependency to 2.0.0. Also ran the formatter.
> [ia-userlist-settings] v1.0.22

- packages/ia-topnav/src/styles/primary-nav.js
https://webarchive.jira.com/browse/WEBDEV-7230
> Top Nav navigation disappears when resizing browser

- packages/ia-topnav/package.json
Top Nav navigation disappears when resizing browser #935 @nsharma123
> [ia-topnav] v1.3.9

- packages/ia-userlist-settings/package.json
- packages/ia-userlist-settings/yarn.lock
Upgrades search-service to v1.4.2 in the ia-userlist-settings package.
> [ia-userlist-settings] Upgrade search service to 1.4.2

- packages/ia-userlist-settings/package.json
- packages/ia-userlist-settings/yarn.lock
New version upgrades search service dependency to the latest version.
> Bump ia-userlist-settings to 1.0.26

- packages/ia-userlist-settings/package.json
- packages/ia-userlist-settings/yarn.lock
Update version of search-service 
**Technical**
Linked to UTC date fix
> Bump ia-userlist-settings to 1.0.27
